#index:
#    path: /main
#    controller: App\Controller\DefaultController::index

accueil: # name de la route 
  path: / #route
  controller: App\Controller\MainController::accueil # fonction reliée à la route